import Head from "next/head";
import Footer from "../../footer/Footer";
import Header from "../../header/Header";
import SideBar from "./SideBar";

const MyAccountLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>NextJS Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="min-h-screen bg-color-background">
          <div className="w-full h-7 bg-[#002D75]"></div>
          <div className="welcome-img h-[170px] w-full"></div>
          <div className="container mx-auto flex mt-10">
            <div className="hidden md:block">
              <SideBar />
            </div>
            <div className="flex-1 px-2 md:px-0">{children}</div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default MyAccountLayout;
