import Head from "next/head";
import Footer from "../../footer/Footer";
import Header from "../../header/Header";

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>NextJS Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div>{children}</div>
        <Footer />
      </main>
    </>
  );
};

export default MainLayout;
